### PR TITLE
Enable legacy-leader-election when necessary for policy spec&status sync

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Similar as https://github.com/open-cluster-management/klusterlet-addon-operator/pull/52

Signed-off-by: Chunxi Luo chuluo@redhat.com

### CODE REVIEW

**Review by mprahl — APPROVED** [review]
/hold for the 2.5 branch

**Comment by hanqiuzh** [comment]
this pr needs rebase

**Comment by ChunxiAlexLuo** [comment]
> this pr needs rebase

Done

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
