### PR TITLE
Set the appmgr imagePullPolicy to IfNotPresent

### PR DESCRIPTION
**Pull request by xiangjingli**
Signed-off-by: Xiangjing Li <xiangli@redhat.com>

https://github.com/open-cluster-management/backlog/issues/17816

### CODE REVIEW

**Comment by xiangjingli** [comment]
Hi Yu, Han, could you help review the PR when you have cycle?  I will cherry pick it to release-2.3 for addressing the BZ issue once the PR is merged to main

**Comment by hanqiuzh** [comment]
This issue is also fixed in klusterletaddonconfig https://github.com/open-cluster-management/klusterlet-addon-controller/pull/77

**Pull request merged**
